package com.micudasoftware.data.database

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a task entity in the Room database.
 *
 * @property id The unique identifier for the task. Auto-generated by Room.
 * @property title The title of the task.
 * @property description A detailed description of the task.
 * @property category The category to which the task belongs.
 * @property startDate The start date of the task in milliseconds since epoch.
 * @property endDate The end date of the task in milliseconds since epoch.
 * @property reminders A list of reminder times in milliseconds since epoch.
 * @property isCompleted Indicates whether the task is completed.
 */
@Entity(tableName = "tasks")
internal data class TaskEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val title: String,
    val description: String,
    val categoryId: Long,
    val startDate: Long,
    val endDate: Long,
    val reminders: List<Long>,
    val isCompleted: Boolean,
)
